import { bmw, bmw1, bmw2, bmw3, bmw4, bmw5, bmw6, tesla, volt, svg, svg1, svg2, svg3, svg4 } from "../../components/img";

const catal = [
    {
        id: 1,
        img: bmw,
        title: "2019 BMW i3",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "350 км + ДВС",
        svg2: svg2,
        test2: "Пробег",
        desc2: "5177 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2019",
        svg4: svg4,
        test4: "Цена",
        desc4: "15800 $",
        btn: "Заказать"
    },
    {
        id: 2,
        img: tesla,
        title: "2018 Tesla Model 3 Mid",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "420 км",
        svg2: svg2,
        test2: "Пробег",
        desc2: "15534 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2018",
        svg4: svg4,
        test4: "Цена",
        desc4: "16800 $",
        btn: "Заказать"
    },
    {
        id: 3,
        img: volt,
        title: "2016 Chevrolet Volt II",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "85 км + ДВС",
        svg2: svg2,
        test2: "Пробег",
        desc2: "26097 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2017",
        svg4: svg4,
        test4: "Цена",
        desc4: "16000 $",
        btn: "Заказать"
    },
    {
        id: 4,
        img: bmw1,
        title: "2013 Tesla Model S60",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "350 км + ДВС",
        svg2: svg2,
        test2: "Пробег",
        desc2: "6786 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2020",
        svg4: svg4,
        test4: "Цена",
        desc4: "18800 $",
        btn: "Заказать"
    },
    {
        id: 5,
        img: bmw2,
        title: "2014 BMW i3 REX",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "420 км",
        svg2: svg2,
        test2: "Пробег",
        desc2: "1553 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2014",
        svg4: svg4,
        test4: "Цена",
        desc4: "15000 $",
        btn: "Заказать"
    },
    {
        id: 6,
        img: bmw3,
        title: "2014 Tesla Model S60",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "85 км + ДВС",
        svg2: svg2,
        test2: "Пробег",
        desc2: "6545 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2014",
        svg4: svg4,
        test4: "Цена",
        desc4: "14500 $",
        btn: "Заказать"
    },
    {
        id: 7,
        img: bmw4,
        title: "2016 Tesla Model X",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "350 км + ДВС",
        svg2: svg2,
        test2: "Пробег",
        desc2: "6777 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2016",
        svg4: svg4,
        test4: "Цена",
        desc4: "19300 $",
        btn: "Заказать"
    },
    {
        id: 8,
        img: bmw5,
        title: "2017 Chevrolet Bolt",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "420 км",
        svg2: svg2,
        test2: "Пробег",
        desc2: "1534 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2017",
        svg4: svg4,
        test4: "Цена",
        desc4: "20200 $",
        btn: "Заказать"
    },
    {
        id: 9,
        img: bmw6,
        title: "2017 Fiat 500e",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "85 км + ДВС",
        svg2: svg2,
        test2: "Пробег",
        desc2: "87097 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2017",
        svg4: svg4,
        test4: "Цена",
        desc4: "14700 $",
        btn: "Заказать"
    },
]
export {catal};
