import { bmw, tesla, volt, svg, svg1, svg2, svg3, svg4 } from "../../img";

const info = [
    {
        id: 1,
        img: bmw,
        title: "2019 BMW i3",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "350 км + ДВС",
        svg2: svg2,
        test2: "Пробег",
        desc2: "5177 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2019",
        svg4: svg4,
        test4: "Цена",
        desc4: "15800 $",
        btn: "Заказать"
    },
    {
        id: 2,
        img: tesla,
        title: "2018 Tesla Model 3 Mid",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "420 км",
        svg2: svg2,
        test2: "Пробег",
        desc2: "15534 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2018",
        svg4: svg4,
        test4: "Цена",
        desc4: "16800 $",
        btn: "Заказать"
    },
    {
        id: 3,
        img: volt,
        title: "2016 Chevrolet Volt II",
        svg: svg,
        test: "Привод",
        desc: "rwd",
        svg1: svg1,
        test1: "Запас хода",
        desc1: "85 км + ДВС",
        svg2: svg2,
        test2: "Пробег",
        desc2: "26097 миль",
        svg3: svg3,
        test3: "Год выпуска",
        desc3: "2017",
        svg4: svg4,
        test4: "Цена",
        desc4: "16000 $",
        btn: "Заказать"
    },
]
export {info};
